#ifndef COLORFILTERCONTROL_DEFINE_H
#define COLORFILTERCONTROL_DEFINE_H

#define CFC_SCREENSIZE          QSize(324, 520)
#define CFC_TITLE_GEOMETRY      QRect(6, 0, 312, 32)

// TODO: add _HORIZON for the horizontal screen

#endif // COLORFILTERCONTROL_DEFINE_H
