#ifndef COLORPICKERCONTROL_DEFINE_H
#define COLORPICKERCONTROL_DEFINE_H

#define CPC_SCREENSIZE          QSize(324, 520)
#define CPC_TITLE_GEOMETRY      QRect(6, 0, 312, 32)

#endif // COLORPICKERCONTROL_DEFINE_H
