#ifndef DESIGNPOLICYDEFINE_H
#define DESIGNPOLICYDEFINE_H

#define SELECT_BUTTON_BG_COLOR_UNSELECTED QColor(13,13,13)
#define SELECT_BUTTON_TEXT_COLOR_UNSELECTED QColor(128,128,128)
#define SELECT_BUTTON_BG_COLOR_SELECTED QColor(89,89,89)
#define SELECT_BUTTON_TEXT_COLOR_SELECTED QColor(255,255,255)
#define SELECT_BUTTON_BG_COLOR_DISABLE QColor(22,22,22)
#define SELECT_BUTTON_TEXT_COLOR_DISABLE QColor(191,191,191)


#endif // DESIGNPOLICYDEFINE_H
